AUG:
    RESIZE_METHOD: 'unpadding' # choice unpadding rangescaling and stepscaling
    TRAIN_INPUT_SIZE: [280, 32]  # crop size for training
    EVAL_INPUT_SIZE: [280, 32]  # crop size for evaluating
    MIRROR: True
    RICH_CROP:
        ENABLE: False
        BLUR: True
        BLUR_RATIO: 0.2
        MAX_ROTATION: 15
        MIN_AREA_RATIO: 0.5
        ASPECT_RATIO: 0.5
        BRIGHTNESS_JITTER_RATIO: 0.5
        CONTRAST_JITTER_RATIO: 0.5
        SATURATION_JITTER_RATIO: 0.5
DATASET:
    DATA_DIR: '/PATH/IMAGE_OCR/SYNTH_CHINESE'
    IMAGE_TYPE: 'rgb'  # choice rgb or rgba
    NUM_CLASSES: 5825
    TEST_FILE_LIST: '/PATH/IMAGE_OCR/SYNTH_CHINESE/labels/test.txt'
    TRAIN_FILE_LIST: '/PATH/IMAGE_OCR/SYNTH_CHINESE/labels/train.txt'
    VAL_FILE_LIST: '/PATH/IMAGE_OCR/SYNTH_CHINESE/labels/val.txt'
    PADDING_VALUE: [127.5, 127.5, 127.5]
    MEAN_VALUE: [0.5, 0.5, 0.5]
    STD_VALUE: [0.5, 0.5, 0.5]
    CPU_MULTI_PROCESS_NUMS: 16
FREEZE:
    MODEL_FILENAME: 'model'
    PARAMS_FILENAME: 'params'
MODEL:
    MODEL_NAME: 'crnn'
    CRNN:
        HIDDEN_UNITS: 256
        HIDDEN_LAYERS: 2
        SEQ_LENGTH: 70
TEST:
    TEST_MODEL: 'weights/crnn_synth_chinese/final'
TRAIN:
    MODEL_SAVE_DIR: 'weights/crnn_synth_chinese/'
    TBOARD_SAVE_DIR: 'tboard/crnn_synth_chinese/'
    MODEL_PARAMS_CONFIG_FILE_NAME: "model_train_config.json"
    RESTORE_FROM_SNAPSHOT:
        ENABLE: False
        SNAPSHOT_PATH: ''
    SNAPSHOT_EPOCH: 8
    BATCH_SIZE: 16
    VAL_BATCH_SIZE: 4
    EPOCH_NUMS: 905
    WARM_UP:
        ENABLE: True
        EPOCH_NUMS: 8
    FREEZE_BN:
        ENABLE: False
    MULTI_GPU:
        ENABLE: True
        GPU_DEVICES: ['0', '1', '2', '3']
        CHIEF_DEVICE_INDEX: 0
SOLVER:
    LR: 0.01
    LR_POLICY: 'cos'
    POLY_DECAY:
        LR_POLYNOMIAL_POWER: 0.95
        LR_POLYNOMIAL_END_LR: 0.000001
    EXP_DECAY:
        DECAY_RATE: 0.1
        APPLY_STAIRCASE: True
    COS_DECAY:
        ALPHA: 0.0
    OPTIMIZER: 'sgd'
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    MOVING_AVE_DECAY: 0.9995
    LOSS_TYPE: 'cross_entropy'
GPU:
    GPU_MEMORY_FRACTION: 0.9
    TF_ALLOW_GROWTH: True
LOG:
    SAVE_DIR: './log'
    LEVEL: INFO
